using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MessageParser.Generators
{
    [Generator]
    public class FilterableWrapperGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m != null);

            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Item1, source.Item2!, spc));
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            
            foreach (var member in classDeclaration.Members)
            {
                if (member is PropertyDeclarationSyntax prop)
                {
                    foreach (var attributeList in prop.AttributeLists)
                    {
                        foreach (var attribute in attributeList.Attributes)
                        {
                            var name = attribute.Name.ToString();
                            if (name == "Filterable" || name == "FilterableAttribute")
                            {
                                return classDeclaration;
                            }
                        }
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
        {
            if (classes.IsDefaultOrEmpty) return;

            var distinctClasses = classes.Distinct();
            var generatedWrappers = new List<(string ClassName, string WrapperName)>();

            foreach (var classDec in distinctClasses)
            {
                var semanticModel = compilation.GetSemanticModel(classDec.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(classDec) is not INamedTypeSymbol classSymbol) continue;

                string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
                string className = classSymbol.Name;
                string wrapperName = $"{className}Filterable";

                var properties = new List<(string RealName, string FriendlyName)>();
                foreach (var member in classSymbol.GetMembers())
                {
                    if (member is IPropertySymbol propSymbol)
                    {
                        var filterableAttr = propSymbol.GetAttributes()
                            .FirstOrDefault(a => a.AttributeClass?.Name == "FilterableAttribute" || a.AttributeClass?.Name == "Filterable");
                        
                        if (filterableAttr != null && filterableAttr.ConstructorArguments.Length > 0)
                        {
                            string friendlyName = filterableAttr.ConstructorArguments[0].Value?.ToString() ?? propSymbol.Name;
                            properties.Add((propSymbol.Name, friendlyName));
                        }
                    }
                }

                if (properties.Count == 0) continue;

                generatedWrappers.Add((className, wrapperName));

                var codeBuilder = new StringBuilder();
                codeBuilder.AppendLine($@"// <auto-generated />
#nullable enable
using System;
using MessageParser.Core.Filtering;
using MessageParser.Core.Messages;

namespace {namespaceName}
{{
    public class {wrapperName} : IFilterable
    {{
        public object WrappedMessage => TypedMessage;
        public Type MessageType => typeof({className});
        public string MessageTypeName => ""{className}"";
        public DateTime ReceivedTime => TypedMessage.ReceivedTime;
        public string Sender => TypedMessage.Sender;
        public string Receiver => TypedMessage.Receiver;

        public {className} TypedMessage {{ get; }}

        public {wrapperName}({className} message)
        {{
            TypedMessage = message ?? throw new ArgumentNullException(nameof(message));
        }}

        public bool ApplyFilter(string propertyName, Func<object?, bool> predicate)
        {{
            if (predicate == null) return true;

            return propertyName.ToUpperInvariant() switch
            {{
                ""SENDER"" => predicate(TypedMessage.Sender),
                ""RECEIVER"" => predicate(TypedMessage.Receiver),");

                foreach (var prop in properties)
                {
                    codeBuilder.AppendLine($@"                ""{prop.RealName.ToUpperInvariant()}"" => predicate(TypedMessage.{prop.RealName}),");
                    if (!string.Equals(prop.RealName, prop.FriendlyName, StringComparison.OrdinalIgnoreCase))
                    {
                        codeBuilder.AppendLine($@"                ""{prop.FriendlyName.ToUpperInvariant()}"" => predicate(TypedMessage.{prop.RealName}),");
                    }
                }

                codeBuilder.AppendLine($@"                _ => false
            }};
        }}
    }}
}}");

                context.AddSource($"{wrapperName}.g.cs", SourceText.From(codeBuilder.ToString(), Encoding.UTF8));
            }

            if (generatedWrappers.Count > 0)
            {
                var factoryBuilder = new StringBuilder();
                factoryBuilder.AppendLine($@"// <auto-generated />
#nullable enable
using System;
using MessageParser.Core.Filtering;
using MessageParser.Core.Messages;

namespace MessageParser.Plugins
{{
    public static class GeneratedFilterableFactory
    {{
        public static IFilterable CreateWrapper(MessageBase message)
        {{
            return message switch
            {{");

                foreach (var wrapper in generatedWrappers)
                {
                    factoryBuilder.AppendLine($@"                {wrapper.ClassName} m => new {wrapper.WrapperName}(m),");
                }

                factoryBuilder.AppendLine($@"                _ => throw new NotSupportedException($""No filterable wrapper generated for message type {{message.GetType().Name}}"")
            }};
        }}
    }}
}}");

                context.AddSource("GeneratedFilterableFactory.g.cs", SourceText.From(factoryBuilder.ToString(), Encoding.UTF8));
            }
        }
    }
}
