using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MessageParser.Generators
{
    [Generator]
    public class MessageEvaluatorGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m != null);

            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Item1, source.Item2!, spc));
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;

            foreach (var member in classDeclaration.Members)
            {
                if (member is PropertyDeclarationSyntax prop)
                {
                    foreach (var attributeList in prop.AttributeLists)
                    {
                        foreach (var attribute in attributeList.Attributes)
                        {
                            var name = attribute.Name.ToString();
                            if (name == "Filterable" || name == "FilterableAttribute")
                            {
                                return classDeclaration;
                            }
                        }
                    }
                }
            }
            return null;
        }

        private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
        {
            if (classes.IsDefaultOrEmpty) return;

            var distinctClasses = classes.Distinct();
            var generatedEvaluators = new List<(string ClassName, string EvaluatorFullName)>();
            var generatedFilterInfos = new List<(string ClassName, string FilterInfoFullName)>();

            foreach (var classDec in distinctClasses)
            {
                var semanticModel = compilation.GetSemanticModel(classDec.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(classDec) is not INamedTypeSymbol classSymbol) continue;

                string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
                string className = classSymbol.Name;
                string evaluatorName = $"{className}MessageEvaluator";
                string filterInfoName = $"{className}FilterInfo";

                var properties = new List<(string RealName, string FriendlyName, string TypeDisplay)>();
                foreach (var member in classSymbol.GetMembers())
                {
                    if (member is IPropertySymbol propSymbol)
                    {
                        var filterableAttr = propSymbol.GetAttributes()
                            .FirstOrDefault(a => a.AttributeClass?.Name == "FilterableAttribute" || a.AttributeClass?.Name == "Filterable");

                        if (filterableAttr != null)
                        {
                            string friendlyName = propSymbol.Name;
                            if (filterableAttr.ConstructorArguments.Length > 0 && filterableAttr.ConstructorArguments[0].Value != null)
                            {
                                friendlyName = filterableAttr.ConstructorArguments[0].Value?.ToString() ?? propSymbol.Name;
                            }
                            properties.Add((propSymbol.Name, friendlyName, propSymbol.Type.ToDisplayString()));
                        }
                    }
                }

                if (properties.Count == 0) continue;

                generatedEvaluators.Add((className, $"{namespaceName}.{evaluatorName}"));
                generatedFilterInfos.Add((className, $"{namespaceName}.{filterInfoName}"));

                // Generate MessageEvaluator
                var evalBuilder = new StringBuilder();
                evalBuilder.AppendLine($@"// <auto-generated />
#nullable enable
using System;
using MessageParser.Core.Filtering;

namespace {namespaceName}
{{
    public class {evaluatorName} : IMessageEvaluator
    {{
        public Type MessageType => typeof({className});

        public bool Evaluate(object message, string propertyName, Func<object?, bool> predicate)
        {{
            if (message is not {className} typedMessage || predicate == null) return false;

            return propertyName.ToUpperInvariant() switch
            {{
                ""SENDER"" => predicate(typedMessage.Sender),
                ""RECEIVER"" => predicate(typedMessage.Receiver),");

                foreach (var prop in properties)
                {
                    evalBuilder.AppendLine($@"                ""{prop.RealName.ToUpperInvariant()}"" => predicate(typedMessage.{prop.RealName}),");
                    if (!string.Equals(prop.RealName, prop.FriendlyName, StringComparison.OrdinalIgnoreCase))
                    {
                        evalBuilder.AppendLine($@"                ""{prop.FriendlyName.ToUpperInvariant()}"" => predicate(typedMessage.{prop.RealName}),");
                    }
                }

                evalBuilder.AppendLine($@"                _ => false
            }};
        }}
    }}
}}");

                context.AddSource($"{evaluatorName}.g.cs", SourceText.From(evalBuilder.ToString(), Encoding.UTF8));

                // Generate FilterInfo
                var infoBuilder = new StringBuilder();
                infoBuilder.AppendLine($@"// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using MessageParser.Core.Filtering;

namespace {namespaceName}
{{
    public class {filterInfoName} : IFilterInfo
    {{
        public Type MessageType => typeof({className});
        public string MessageTypeName => ""{className}"";

        public IReadOnlyDictionary<string, Type> FilterableProperties {{ get; }} = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase)
        {{
            {{ ""Sender"", typeof(string) }},
            {{ ""Receiver"", typeof(string) }},");

                foreach (var prop in properties)
                {
                    infoBuilder.AppendLine($@"            {{ ""{prop.FriendlyName}"", typeof({prop.TypeDisplay}) }},");
                    if (!string.Equals(prop.RealName, prop.FriendlyName, StringComparison.OrdinalIgnoreCase))
                    {
                        infoBuilder.AppendLine($@"            {{ ""{prop.RealName}"", typeof({prop.TypeDisplay}) }},");
                    }
                }

                infoBuilder.AppendLine($@"        }};
    }}
}}");

                context.AddSource($"{filterInfoName}.g.cs", SourceText.From(infoBuilder.ToString(), Encoding.UTF8));
            }

            if (generatedEvaluators.Count > 0)
            {
                var factoryBuilder = new StringBuilder();
                factoryBuilder.AppendLine($@"// <auto-generated />
#nullable enable
using System.Collections.Generic;
using MessageParser.Core.Filtering;

namespace MessageParser.Plugins
{{
    public static class GeneratedMessageEvaluators
    {{
        public static IEnumerable<IMessageEvaluator> GetAll()
        {{");

                foreach (var evaluator in generatedEvaluators)
                {
                    factoryBuilder.AppendLine($@"            yield return new {evaluator.EvaluatorFullName}();");
                }

                factoryBuilder.AppendLine($@"        }}
    }}

    public static class GeneratedFilterInfos
    {{
        public static IEnumerable<IFilterInfo> GetAll()
        {{");

                foreach (var info in generatedFilterInfos)
                {
                    factoryBuilder.AppendLine($@"            yield return new {info.FilterInfoFullName}();");
                }

                factoryBuilder.AppendLine($@"        }}
    }}
}}");

                context.AddSource("GeneratedEvaluatorsAndFilterInfos.g.cs", SourceText.From(factoryBuilder.ToString(), Encoding.UTF8));
            }
        }
    }
}
